name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19' # The Go version to download (if necessary) and use.

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: install-js-libs
        run: |
          npm install -g postcss postcss-cli
          npm install autoprefixer

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: go-

      - name: check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with: 
          files: "~/go/bin/hugo"

      - name: install-hugo
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          mkdir -p ~/go/src/github.com/
          cd ~/go/src/github.com/
          git clone https://github.com/gohugoio/hugo.git -b v0.105.0
          cd hugo
          go install --tags extended

      - name: build-hugo
        run:
          hugo --minify

      - name: deploy-pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: www.ondakyo.org
